id: PA08515EF
initial_creation_type: ocr
source_metadata:
  volumes:
    526ec67edcd94d2da8825915f15f79b2:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སྤེལ་མར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
